### ISSUE TITLE
[BUG]: Zerkerlot's damage is wrong

### ISSUE THREAD

**Issue by TCZapper** [gakiloroth/gakiloroth.github.io#6] opened 2020-07-15 03:08 UTC
**Describe the bug**
I ran a test against Sky-type servants with Lancelot and noticed 2 issues:
1. When I select Lancelot his attribute defaults to Sky, but it should be Earth according to: https://fategrandorder.fandom.com/wiki/Lancelot
2. After fixing that, his damage appears to be missing the class's 1.1x modifier. I did not forget to include his 10% attack buff from his NP. This is compared to my own manual calculation and gamepress's calculator.

For the second thing, berserker is misspelled here:
https://github.com/gakiloroth/gakiloroth.github.io/blob/afc1a616db3808d630078d49af510b7d0580edd7/_site/js/main.js#L1767

**Comment by gakiloroth** [comment] 2020-07-15 04:56
Thanks for finding this! pushed a fix, let me know if it works as intended now

**Closed** 2020-07-15 05:00 UTC
Labels: bug
